Repository DIT112-V20/group-02, pull requests merged in 2020-05, with the labels that each got.

#34 App updates
  app/app/build.gradle
  app/app/src/main/java/com/example/app/ConnectActivity.kt
  app/app/src/main/java/com/example/app/MainActivity.kt
  app/app/src/main/res/layout/activity_connect.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/values/strings.xml
Labels: Sprint#3, enhancement

#39 Improved app layout
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/res/drawable-hdpi/background.png
  app/app/src/main/res/drawable-hdpi/background_drive.png
  app/app/src/main/res/drawable-ldpi/background.png
  app/app/src/main/res/drawable-ldpi/background_drive.png
  app/app/src/main/res/drawable-mdpi/background.png
  app/app/src/main/res/drawable-mdpi/background_drive.png
  app/app/src/main/res/drawable-v24/main_gradient.xml
  app/app/src/main/res/drawable-xhdpi/background.png
  app/app/src/main/res/drawable-xhdpi/background_drive.png
  app/app/src/main/res/drawable-xxhdpi/background.png
  app/app/src/main/res/drawable-xxhdpi/background_drive.png
  app/app/src/main/res/drawable-xxxhdpi/background.png
  app/app/src/main/res/drawable-xxxhdpi/background_drive.png
  app/app/src/main/res/drawable/button.xml
  app/app/src/main/res/drawable/button_help.xml
  app/app/src/main/res/drawable/ic_airport_shuttle_24px.xml
  app/app/src/main/res/drawable/ic_arrow_back_24px.xml
  app/app/src/main/res/drawable/ic_arrow_downward_24px.xml
  app/app/src/main/res/drawable/ic_arrow_forward_24px.xml
  app/app/src/main/res/drawable/ic_arrow_upward_24px.xml
  app/app/src/main/res/drawable/ic_cancel_24px.xml
  app/app/src/main/res/drawable/ic_pan_tool_24px.xml
  app/app/src/main/res/font/amiko_semibold.xml
  app/app/src/main/res/font/segoebold.ttf
  app/app/src/main/res/font/segoeitalic.ttf
  app/app/src/main/res/font/segoeitalicbold.ttf
  app/app/src/main/res/font/segoeui.ttf
  app/app/src/main/res/layout/activity_connect.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/values/colors.xml
  app/app/src/main/res/values/font_certs.xml
  app/app/src/main/res/values/preloaded_fonts.xml
  app/app/src/main/res/values/strings.xml
Labels: Sprint#4

#40 Improved obstacle avoidance
  SmartCar/SmartCar.ino
Labels: Sprint#4

#49 Improve app layout
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/example/app/ConnectActivity.kt
  app/app/src/main/java/com/example/app/HelpActivity.kt
  app/app/src/main/java/com/example/app/MainActivity.kt
  app/app/src/main/res/drawable-hdpi/background_help.png
  app/app/src/main/res/drawable-ldpi/background_help.png
  app/app/src/main/res/drawable-mdpi/background_help.png
  app/app/src/main/res/drawable-xhdpi/background_help.png
  app/app/src/main/res/drawable-xxhdpi/background_help.png
  app/app/src/main/res/drawable-xxxhdpi/background_help.png
  app/app/src/main/res/drawable/car_control_manual.JPG
  app/app/src/main/res/drawable/control_car_tutorial_image.JPG
  app/app/src/main/res/drawable/decrease_and_increase_speed.JPG
  app/app/src/main/res/drawable/drive_mode_button.JPG
  app/app/src/main/res/drawable/ic_acellerate.xml
  app/app/src/main/res/drawable/ic_airport_shuttle_24px.xml
  app/app/src/main/res/drawable/ic_arrow_back_24px.xml
  app/app/src/main/res/drawable/ic_arrow_downward_24px.xml
  app/app/src/main/res/drawable/ic_arrow_forward_24px.xml
  app/app/src/main/res/drawable/ic_arrow_upward_24px.xml
  app/app/src/main/res/drawable/ic_cancel_24px.xml
  app/app/src/main/res/drawable/ic_decrease_speed.xml
  app/app/src/main/res/drawable/ic_downwards_arrow.xml
  app/app/src/main/res/drawable/ic_left_arrow.xml
  app/app/src/main/res/drawable/ic_return.xml
  app/app/src/main/res/drawable/ic_right_arrow.xml
  app/app/src/main/res/drawable/ic_upwards_arrow.xml
  app/app/src/main/res/drawable/stop_button_picture.JPG
  app/app/src/main/res/drawable/toggle_bluetooth.JPG
  app/app/src/main/res/layout/activity_connect.xml
  app/app/src/main/res/layout/activity_help.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/values/strings.xml
  app/app/src/main/res/values/styles.xml
Labels: Sprint#5

#51 Vibrate feedback
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/java/com/example/app/ConnectActivity.kt
Labels: enhancement

#52 Implement grayed out buttons
  app/app/src/main/java/com/example/app/ConnectActivity.kt
  app/app/src/main/res/drawable/control_acellerate.xml
  app/app/src/main/res/drawable/control_decrease.xml
  app/app/src/main/res/drawable/control_downwards_arrow.xml
  app/app/src/main/res/drawable/control_left_arrow.xml
  app/app/src/main/res/drawable/control_right_arrow.xml
  app/app/src/main/res/drawable/control_upwards_arrow.xml
  app/app/src/main/res/drawable/ic_acellerate_gray.xml
  app/app/src/main/res/drawable/ic_decrease_speed_gray.xml
  app/app/src/main/res/drawable/ic_downwards_arrow_gray.xml
  app/app/src/main/res/drawable/ic_left_arrow_gray.xml
  app/app/src/main/res/drawable/ic_right_arrow_gray.xml
  app/app/src/main/res/drawable/ic_upwards_arrow_gray.xml
  app/app/src/main/res/layout/activity_connect.xml
Labels: Sprint#6

#59 finalized readme file
  README.md
Labels: enhancement

#60 Implement app icon
  app/app/src/main/AndroidManifest.xml
  app/app/src/main/logo_black-playstore.png
  app/app/src/main/res/drawable/logo_black_background.xml
  app/app/src/main/res/drawable/logo_white.png
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/mipmap-anydpi-v26/logo_black.xml
  app/app/src/main/res/mipmap-anydpi-v26/logo_black_round.xml
  app/app/src/main/res/mipmap-hdpi/logo_black.png
  app/app/src/main/res/mipmap-hdpi/logo_black_foreground.png
  app/app/src/main/res/mipmap-hdpi/logo_black_round.png
  app/app/src/main/res/mipmap-mdpi/logo_black.png
  app/app/src/main/res/mipmap-mdpi/logo_black_foreground.png
  app/app/src/main/res/mipmap-mdpi/logo_black_round.png
  app/app/src/main/res/mipmap-xhdpi/logo_black.png
  app/app/src/main/res/mipmap-xhdpi/logo_black_foreground.png
  app/app/src/main/res/mipmap-xhdpi/logo_black_round.png
  app/app/src/main/res/mipmap-xxhdpi/logo_black.png
  app/app/src/main/res/mipmap-xxhdpi/logo_black_foreground.png
  app/app/src/main/res/mipmap-xxhdpi/logo_black_round.png
  app/app/src/main/res/mipmap-xxxhdpi/logo_black.png
  app/app/src/main/res/mipmap-xxxhdpi/logo_black_foreground.png
  app/app/src/main/res/mipmap-xxxhdpi/logo_black_round.png
  app/app/src/main/res/values/logo_black_background.xml
Labels: Sprint#7

#62 Vibrations and speedchange fix
  app/app/src/main/java/com/example/app/ConnectActivity.kt
Labels: Sprint#7
