Repository DIT112-V20/group-02, pull requests merged in 2020-04, with the labels that each got.

#7 Add Car Control to the SmartCar
  SmartCar/SmartCar.ino
Labels: Sprint#1

#8 Bluetooth
  SmartCar/SmartCar.ino
Labels: Sprint#1

#11 Added speedcontrol
  SmartCar/SmartCar.ino
Labels: Sprint#1

#12 Implemented smartcar class
  SmartCar/SmartCar.ino
Labels: Sprint#1

#16 Stable bluetoothconnection.
  SmartCar/SmartCar.ino
Labels: Sprint#1

#20 Lidar guidance
  .travis.yml
  SmartCar/SmartCar.ino
Labels: Sprint#2, enhancement

#25 Manual/automatic Control.
  SmartCar/SmartCar.ino
Labels: Sprint#2

#27 Basic mobile app
  .travis.yml
  app/app/src/main/java/com/example/app/ConnectActivity.kt
  app/app/src/main/java/com/example/app/MainActivity.kt
  app/app/src/main/res/layout/activity_connect.xml
  app/app/src/main/res/layout/activity_main.xml
  app/app/src/main/res/values/strings.xml
Labels: enhancement

#30 Implemented cruise control
  SmartCar/SmartCar.ino
Labels: Sprint#3
